### ISSUE TITLE
How to use code generation

### ISSUE THREAD

**Issue by Wxianpeng** [lukelorusso/VerticalSeekBar#8]
**For example:** 

       VerticalSeekBar  verticalSeekBar= new VerticalSeekBar(this,null);
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(200, 500);
        params.setMargins(100, 200, 0, 0);
        verticalSeekBar.setLayoutParams(params);

**Some errors occurred**

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lukelorusso.verticalseekbarsample/com.lukelorusso.verticalseekbarsample.Main2Activity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter attrs
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter attrs
        at com.lukelorusso.verticalseekbar.VerticalSeekBar.<init>(Unknown Source:7)
        at com.lukelorusso.verticalseekbarsample.Main2Activity.onCreate(Main2Activity.java:16)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
2020-04-16 14:15:53.269 720-2535/? E/iMonitor: FaultDetect: DUMPTOOL_PRINTF return.

**Comment by lukelorusso** [comment]
Hi Wxianpeng,

this is an issue related to constructors. The fix will be released in the next version.
Thank you for your feedback!
